/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_krasutski_jni_WUSB */

#ifndef _Included_com_krasutski_jni_WUSB
#define _Included_com_krasutski_jni_WUSB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_krasutski_jni_WUSB
 * Method:    AccessUSB
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_krasutski_jni_WUSB_AccessUSB
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_krasutski_jni_WUSB
 * Method:    OpenUSB
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_krasutski_jni_WUSB_OpenUSB
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_krasutski_jni_WUSB
 * Method:    CloseUSB
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_krasutski_jni_WUSB_CloseUSB
  (JNIEnv *, jobject);

/*
 * Class:     com_krasutski_jni_WUSB
 * Method:    PurgeUSB
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_krasutski_jni_WUSB_PurgeUSB
  (JNIEnv *, jobject);

/*
 * Class:     com_krasutski_jni_WUSB
 * Method:    RxFrameUSB
 * Signature: (ILjava/lang/Byte;Ljava/lang/Byte;Ljava/lang/Byte;Ljava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_krasutski_jni_WUSB_RxFrameUSB
  (JNIEnv *, jobject, jint, jobject, jobject, jobject, jobject);

/*
 * Class:     com_krasutski_jni_WUSB
 * Method:    TxFrameUSB
 * Signature: (BBBLjava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_krasutski_jni_WUSB_TxFrameUSB
  (JNIEnv *, jobject, jbyte, jbyte, jbyte, jobject);

/*
 * Class:     com_krasutski_jni_WUSB
 * Method:    NumUSB
 * Signature: (Ljava/lang/Integer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_krasutski_jni_WUSB_NumUSB
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
